### ISSUE TITLE
PanMouseMode does not render the buffered map image correctly when the top edge of the projection is at or above Lat 90

### ISSUE THREAD

**Issue by kwg1990** [OpenMap-java/openmap#23]
In the class PanMouseMode, line 253, in method mousePressed. the paintedImage is set to 
paintedImage = new OMRaster(ul.getY(), ul.getX(), 0, 0, bufferedMapImage);
if the ul.getY() call returns "90" then the image will not be rendered for some reason. Changing that line to this solves the problem and everything renders as expected:
paintedImage = new OMRaster(ul.getY() < 90 ? ul.getY() : 89.9999999999, ul.getX(), 0, 0, bufferedMapImage);

**Comment by dfdietrick** [comment]
Hi!

Thanks for the heads-up!  I’ve updated the code for the next release.

- Don
